
#!/usr/bin/python

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


fib = [1,2]

def next_fib(f):
    for f in fib:
        i = fib.index(f)
    return f+fib[i-1]


for g in fib:
    if next_fib(g) <= 4000000:
        fib.append(next_fib(g))

even_fib = []
for g in fib:
    if g % 2 == 0:
        even_fib.append(g)

print "The fibbonaci numbers are" + str(fib)
print "The even ones are" + str(even_fib)
print str(sum(even_fib))
